import math

# General
BUFFER_SIZE = 500
SEED = 69

# Dataset
DATASET_PATH = 'dataset/'

# Model train settings
IMAGE_SIZE = 64
IMAGE_CHANNEL = 3
BATCH_SIZE = 32
EPOCHS = 300

FILTERS_MIN = 64
FILTERS_MAX = 512

IMAGE_MIN_SIZE = 4

BLOCKS_COUNT = round(math.log(IMAGE_SIZE / IMAGE_MIN_SIZE, 2))

# Model hyperparameters
MAPPING_LAYERS = 8
LATENT_DIM = 128
LEAKY_RELU_ALPHA = 0.2
KERNEL_SIZE = 3

ADAM_LEARNING_RATE = 0.02
ADAM_BETA1 = 0
ADAM_BETA2 = 0.99
ADAM_EPSILON = 1e-8

L2_REGULARIZATION = 0.02

SMOOTH = 0.1

# Image Saving Callback
IMAGE_OUTPUT_PATH = 'bce_images_26032023/'
SAVE_IMAGE_FREQUENCY = 500
MARGIN = IMAGE_SIZE // 8
OUTPUT_SHAPE = (4, 4)

MODEL_OUTPUT_PATH = 'bce_model_26032023/'
